<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>8aad6174-3b44-4b40-a121-73823b436b7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wizardProfile']/app-nuhshome/div/div/div[2]/div/div/div/div/div[2]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pull-right.land > div.img_tab_health > a > img[alt=&quot;e-service&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>e-service</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/MedicationRefill/Content/assets/img/refill.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizardProfile&quot;)/app-nuhshome[1]/div[@class=&quot;wizard-container&quot;]/div[@class=&quot;wizard-box&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-8 col-sm-offset-2&quot;]/div[@class=&quot;wizard-footer nuhs&quot;]/div[@class=&quot;pull-right land&quot;]/div[@class=&quot;img_tab_health&quot;]/a[1]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wizardProfile']/app-nuhshome/div/div/div[2]/div/div/div/div/div[2]/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='e-service'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
