<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Queenstown Polyclinic_ntfgh</name>
   <tag></tag>
   <elementGuidId>5f80948a-acbd-48ca-9392-2028518ec03d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='3']/div/div/img)[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.ntfgh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Ng Teng Fong General Hospital</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ntfgh</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/MedicationRefill/Content/assets/img/ntfgh.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizardProfile&quot;)/app-selector[1]/div[@class=&quot;wizard-container&quot;]/div[1]/div[@class=&quot;wizard-box1&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-sm-offset-0 res-box&quot;]/div[@class=&quot;row clearfix insti-wrap&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-6 col-xs-12 insti-box&quot;]/div[@class=&quot;info-box-new&quot;]/a[@id=&quot;3&quot;]/div[@class=&quot;info-box bg-cyan hover-expand-effect&quot;]/div[@class=&quot;icon&quot;]/img[@class=&quot;ntfgh&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='3']/div/div/img)[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Ng Teng Fong General Hospital']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
